### ISSUE TITLE
Single dash arguments (like the kind Bitcoin Core use) set as series of "true" flags.

### ISSUE THREAD

**Issue by pinheadmz** [bcoin-org/bcfg#5]
This is just a documentation of user error, perhaps nothing to fix. But I want a reference posted in case someone else does this.

Consider you're working with Bitcoin Core and you accidentally try to start bcoin with:
```
$ bcoin -blocksonly
```

What happens is the following:

Strictly because of the single dash, `blocksonly` gets interpreted as a series of single-letter keys (`b`, `l`, `o`, `c`...) , and sets all the corresponding values to `"true"` (the STRING, not a boolean). In the case of the letter `n` an "alias" already exists, so the value of `network` is set to `"true"`:

https://github.com/bcoin-org/bcfg/blob/1216c775832c2e138ae6451912a27ba496dc4386/lib/config.js#L908-L923

So: 
```
{
  b: 'true',
  l: 'true',
  o: 'true',
  c: 'true',
  k: 'true',
  s: 'true',
  network: 'true',
  y: 'true'
}
```

As bcoin continues to process the configuration parameters, it will alert the user the network is invalid:

```
$ bcoin -blocksonly
/Users/matthewzipkin/Desktop/work/bcoin/node_modules/bsert/lib/assert.js:84
    throw new AssertionError({
    ^

AssertionError [ERR_ASSERTION]: Unknown network.
    at Function.create (/Users/matthewzipkin/Desktop/work/bcoin/lib/protocol/network.js:135:5)
    at Function.get (/Users/matthewzipkin/Desktop/work/bcoin/lib/protocol/network.js:181:22)
    at new Node (/Users/matthewzipkin/Desktop/work/bcoin/lib/node/node.js:49:28)
    at new FullNode (/Users/matthewzipkin/Desktop/work/bcoin/lib/node/fullnode.js:40:5)
    at Object.<anonymous> (/Users/matthewzipkin/Desktop/work/bcoin/bin/node:41:14)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  type: 'AssertionError',
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  generatedMessage: false,
  actual: undefined,
  expected: true,
  operator: '=='
}
```

**Comment by nodech** [comment]
I believe there's nothing to fix here.

There are several argument passing conventions, but I believe most popular is GNU getopt (what you see in bcfg). But not everyone follows this convention, (e.g. golangs `flag` does not follow this convention and you have to use `getopt` package) Bitcoin is same.
I don't it's fine (and pretty flexible) to use getopt way in the bcfg.
